services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    networks:
      - bitcoin-hoje-network

networks:
  bitcoin-hoje-network:
    external: true
