services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./frontend-build:/app/dist
    networks:
      - bitcoin-hoje-network

networks:
  bitcoin-hoje-network:
    external: true
